# Kubernetes Service Account for Harbor with IRSA
#
# This service account is annotated with an IAM role ARN, which enables
# IAM Roles for Service Accounts (IRSA). When pods use this service account,
# they automatically receive temporary AWS credentials to assume the IAM role.
#
# Prerequisites:
#   1. EKS cluster with OIDC provider configured
#   2. IAM role created with trust policy for this service account
#   3. IAM role has permissions for S3 and KMS access
#
# Usage:
#   1. Replace ${HARBOR_ROLE_ARN} with your IAM role ARN
#   2. Apply: kubectl apply -f service-account.yaml
#
# The annotation 'eks.amazonaws.com/role-arn' is the key that enables IRSA.
# When a pod uses this service account, the EKS pod identity webhook will:
#   - Inject AWS_ROLE_ARN environment variable
#   - Inject AWS_WEB_IDENTITY_TOKEN_FILE environment variable
#   - Mount a projected service account token at the specified path
#   - AWS SDK automatically uses these to assume the IAM role

apiVersion: v1
kind: ServiceAccount
metadata:
  name: harbor-registry
  namespace: harbor
  annotations:
    # CRITICAL: This annotation links the service account to the IAM role
    # Replace with your actual IAM role ARN
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/HarborS3Role
  labels:
    app: harbor
    component: registry
    security: irsa-enabled
